### ISSUE TITLE
Incorrect benchmark results

### ISSUE THREAD

**Issue by povilasb** [fastio/pedis#10]
In case of 8 threads there is no Redis bar:
https://github.com/fastio/pedis/blob/master/docs/benchmark.png

And I would really like to know those numbers :)

**Comment by fastio** [comment]
hi, Redis is single threaded. These is no way to run one instance of Redis  with 8 threads, but Pedis runs in single process with mulit-threads.

**Comment by povilasb** [comment]
Alright, cool :)
