### ISSUE TITLE
Build failure with GCC 4.9

### ISSUE THREAD

**Issue by akashgoswami** [fastio/pedis#12]
The newly introduced <experimental/vector> are not available with older libstd++. They are introduced in g++ 6.3 onwards. Also -Werror option needs to be removed in order to build successfully.  

Kindly updated the build instructions.

**Comment by fastio** [comment]
@akashgoswami . Thank you for reporting the issue. I have updated the building instructions. https://github.com/fastio/pedis/commit/cdad9eaeb806adf5829fe37f29120a4e4d5561c0

**Comment by akashgoswami** [comment]
Look great. Thanks a lot!
