### ISSUE TITLE
Build failure with g++-5

### ISSUE THREAD

**Issue by convexcat** [fastio/pedis#16]
Looks like the <experimental/vector> is not supported in g++5.
Here is my g++ output

[15/222] CXX build/debug/hll.o
FAILED: g++-5 -MD -MT build/debug/hll.o -MF build/debug/hll.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -I build/debug/gen  -Ibuild/debug/gen/seastar -Ibuild/debug/gen/seastar/seastar -I build/debug/seastar/c-ares -I. -I./utils -I./seastar -I./seastar/fmt -std=gnu++1y -g  -Wall -Werror -Wno-error-deprecated -fvisibility=hidden -pthread  -U_FORTIFY_SOURCE  -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/debug/hll.o hll.cc
In file included from hll.cc:22:0:
common.hh:46:32: fatal error: experimental/vector: No such file or directory
compilation terminated.

**Comment by fastio** [comment]
Hi @convexcat, please upgrade your c++ compiler to the higher version, such as 6.2.

**Comment by convexcat** [comment]
I've got problems when compiling seastar using g++6.3, can you tell me what libboost version you have?
FAILED: g++-6 -MD -MT build/release/init.o -MF build/release/init.o.d -O2 -I build/release/gen  -Ibuild/release/gen/seastar -Ibuild/release/gen/seastar/seastar -I build/release/seastar/c-ares -I. -I./utils -I./seastar -I./seastar/fmt -std=gnu++1y -g  -Wall  -Wno-error-deprecated -fvisibility=hidden -pthread  -U_FORTIFY_SOURCE  -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/init.o init.cc
In file included from /usr/include/boost/config.hpp:61:0,
                 from /usr/include/boost/intrusive/detail/config_begin.hpp:14,
                 from /usr/include/boost/intrusive/list.hpp:17,
                 from ./seastar/core/timer-set.hh:21,
                 from ./seastar/core/timer.hh:29,
                 from ./seastar/core/future-util.hh:32,
                 from ./seastar/core/iostream-impl.hh:26,
                 from ./seastar/core/iostream.hh:227,
                 from ./seastar/core/reactor.hh:26,
                 from ./seastar/core/sharded.hh:24,
                 from ./seastar/core/distributed.hh:24,
                 from init.hh:26,
                 from init.cc:23:
/usr/include/boost/multiprecision/cpp_int.hpp:181:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
/usr/include/boost/multiprecision/cpp_int.hpp:404:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
/usr/include/boost/multiprecision/cpp_int.hpp:556:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));

**Comment by convexcat** [comment]
OK, I solved the last problem using boost1.64.
And '-lyaml-cpp' option needs to be to the ldflags to work correctly.
