### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [fastio/pedis#2]
I would like to point out that identifiers like "[`_DICT_HH`](https://github.com/fastio/pedis/blob/df9fa70d4caef634b4f5622d2f34f642362b7061/src/dict.hh#L19)" and "[`_REDIS_HH`](https://github.com/fastio/pedis/blob/89e293fdc4fcf3388de1e93e3456a8df94ead180/src/redis.hh#L18)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by fastio** [comment]
Thank for your advise, and I take it.

**Comment by elfring** [comment]
How do you think about to avoid that [this software](https://github.com/fastio/pedis/commit/e6fc7557c38ea72f5ce0496e8f24e20852595206#diff-e23021df7f5334ffa3009bf4f630e62cL18 "Update candidate") [depends on undefined behaviour](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Avoid undefined behaviour?")?
