### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by qzfzz** [fastio/pedis#20]
when compiling on commit id: 2f5f14996d539520846239b55d5df6e7e3f0320b
common.hh:46:32: fatal error: experimental/vector: No such file or directory

**Comment by fastio** [comment]
I'll fix it tomorrow.

**Comment by fastio** [comment]
Please checkout the master branch, and try to compile it.  The error is fixed.

**Comment by qzfzz** [comment]
thanks
