### ISSUE TITLE
Ubuntu16.4安装过程需要补充的依赖包

### ISSUE THREAD

**Issue by szoliver** [fastio/pedis#4]
安装包，ubuntu-16.04.1-desktop-amd64.iso在Oracle VM VirtualBox中安装：
1.sudo apt-get install libgnutls-dev
2.sudo apt-get install \*protobuf\*
因为缺少头文件和代码文件，含protobuf的包太多，试了几个都不对，干脆全装了。
3.sudo apt-get install libsctp-dev lksctp-tools
4.sudo apt-get install liblz4*
本次安装使用默认的gcc5.4.1

**Comment by fastio** [comment]
thanks

**Comment by catroot** [comment]
Don`t forget about libboost-dev and ninja-build

sudo apt install libboost-dev ninja-build
