### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by hustnn** [fastio/pedis#5]
build/release/db.o: In function `_ZN20shared_ptr_count_forIN7seastar7metrics4impl17registered_metricEEC4IJRNS2_9data_typeESt8functionIFNS2_12metric_valueEvEERNS1_11descriptionERbEEEDpOT_':
/home/hustnn/redis/pedis/./seastar/core/shared_ptr.hh:329: undefined reference to `seastar::metrics::impl::registered_metric::registered_metric(seastar::metrics::impl::data_type, std::function<seastar::metrics::impl::metric_value ()>, seastar::metrics::description, bool)'
...

**Comment by fastio** [comment]
Cloud you provide more information about  OS, GCC?

**Comment by hustnn** [comment]
I already solved it. 
I use the latest seaster. Some new files are not included in the config file. I revised the config file and it can be compiled successfully. 
Thanks.
