### ISSUE TITLE
fatal: clone of 'git@github.com:scylladb/seastar.git' failed

### ISSUE THREAD

**Issue by catroot** [fastio/pedis#6]
git submodule update --init --recursive

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:scylladb/seastar.git' into submodule path 'seastar' failed

**Comment by WeissGotsman** [comment]
same here

**Comment by catroot** [comment]
there must be a 'https://github.com/scylladb/seastar.git' url instead of  'git@github.com:scylladb/seastar.git' to clone repo.
i have fixed this manually to get it work.

**Comment by fastio** [comment]
I have fixed this problem

**Comment by catroot** [comment]
Now i`ve got
```
git submodule update --init --recursive
fatal: no submodule mapping found in .gitmodules for path 'tests/gtest'

```
