### ISSUE TITLE
Is Pedis production ready?

### ISSUE THREAD

**Issue by yushengery** [fastio/pedis#9]
It's an awesome project, can I use it in production environment?
Is master-slave replication available ?
Great thanks.

**Comment by fastio** [comment]
It's still under development, and has not released a stable version. The feature of MS replication is already bing planned.  At present, this project is progressing well.  A stable version for production environment will be release in few months.

**Comment by yushengery** [comment]
glad to hear that.
Is there any performance enhancement querying from localhost?

**Comment by fastio** [comment]
of course.
